### ISSUE TITLE
Can't run Install.sh

### ISSUE THREAD

**Issue by B14ckAc321** [niizam/vantage#1]
Hello, I followed the steps for the installation as written on the README file, unfortunately when I get to the step "sudo ./install.sh", it tells me "sudo: ./install.sh: command not found".
But if I do "ls" I get "icon.png install.sh LICENSE README.md uninstall.sh vantage.desktop vantage.sh", so install.sh is present.
I use Fedora Linux 36 (Workstation Edition Prerelease), but also with fedora 35 it didn't work.
I have a Lenovo ThinkBook 14-IIL, and lenovo vantge would come in handy.
If anyone knows how to fix it please let me know.

**Comment by MeowcaTheoRange** [comment]
You need to mark the shell script as executable. It the console says nothing, check your whisker/applications menu for it afterwards

**Comment by niizam** [comment]
> Hello, I followed the steps for the installation as written on the README file, unfortunately when I get to the step "sudo ./install.sh", it tells me "sudo: ./install.sh: command not found". But if I do "ls" I get "icon.png install.sh LICENSE README.md uninstall.sh vantage.desktop vantage.sh", so install.sh is present. I use Fedora Linux 36 (Workstation Edition Prerelease), but also with fedora 35 it didn't work. I have a Lenovo ThinkBook 14-IIL, and lenovo vantge would come in handy. If anyone knows how to fix it please let me know.

read the installation again
