### ISSUE TITLE
Installing is not possible

### ISSUE THREAD

**Issue by Ladylunix77** [niizam/vantage#13]
Hi,

after entering the command on Linux Mint virginia, I have received this message: git clone https://github.com/niizam/vantage.git
cd vantage
The command 'git' was not found, but can be installed with
sudo apt install git
bash: cd: vantage: File or directory not found

How do I proceed from here?

I am a newbie on Linux. Many thanks in advance for you help! I wanted to install this on my Thinkpad W530, as the fans are driving me crazy, (too loud).

Lunix

**Comment by niizam** [comment]
Read through the output log, and comprehend it first. (`The command 'git' was not found, but can be installed with
sudo apt install git`).
Therefore you can run this first:
```bash
 sudo apt install git
 ```

**Comment by Ladylunix77** [comment]
Thank you, I did not see the OBVIOUS.

**Comment by Ladylunix77** [comment]
Installing worked fine, but:

I can only edit 
-camera
-microfone and .wifi on this. Is there an option to add fan control?

**Comment by niizam** [comment]
> Installing worked fine, but:
> 
> I can only edit -camera -microfone and .wifi on this. Is there an option to add fan control?

There isn't, because this was made specifically for my IdeaPad Gaming 3.
And I have no idea how to make the fan control work.
