### ISSUE TITLE
install fail on endeavourOS

### ISSUE THREAD

**Issue by BackMountainDevil** [niizam/vantage#5]
this os is based on arch too.

solution: add ` | “endeavouros”` in install.sh Line 10

test install succeed.

conserve-mode work on xiaoxin pro13 are

Thank you for your work

**Comment by thuyencode** [comment]
I just made [a pull request](https://github.com/niizam/vantage/pull/9) that will fix your problem. Every single Arch-based distros has `ID_LIKE=arch` in their `/etc/os-release` file
